title: Mindblown
author: James Kim
email: jamesdaehokim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where creation manifests.

# social links
twitter_username: jamesdaehokim
github_username:  jkim3360

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
